### ISSUE TITLE
Instructions ambiguity

### ISSUE THREAD

**Issue by jaredbidlow** [sillygwailo/Slack-Twitter#11]
For deploying to Heroku, if I only follow steps 1-4, why do I have to enter a Twitter app's environment variables?

**Comment by sillygwailo** [comment]
@jaredbidlow Because you need a Twitter "app" (one from apps.twitter.com, not a client app) to give the Slack bot permission to post tweets and read your timeline. You're essentially manually authenticating your Twitter account to read and post tweets.

(Sorry for the delay in responding, I didn't see the initial notification of this.)
